using Pkg

Pkg.add(Pkg.PackageSpec(name="Makie", version="0.19.12")) # Registered GeometryPrimitives (v0.4.6) is only compatible with the old version Makie (v0.19.12)
Pkg.add("GeometryPrimitives") # (v0.4.6)
Pkg.add("LinearAlgebra")
Pkg.add("Plots")
Pkg.add("Printf")
Pkg.add("Random")
Pkg.add("SparseArrays")
Pkg.add("Statistics")
Pkg.add("Test")
Pkg.add("MPI")
Pkg.add("FFTW")
Pkg.add("MAT")
Pkg.add("LaTeXStrings")
